[package]
name = "windows_wrapper"
version = "0.1.0"
edition = "2024"

[dependencies]
widestring = "1.2.1"
windows = { version = "0.62.2", features = ["Win32_Foundation", "Win32_System_SystemServices", "Win32_UI_WindowsAndMessaging"] }

